# -*- coding: utf-8 -*-
"""Brain_Tumour_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J23bKjNu9T3kyuF6VjGg1A3vvNYUD4Bz
"""

!pip -q install kagglehub tensorflow scikit-learn matplotlib seaborn pandas pillow openpyxl

# Import Libraries
import os
from pathlib import Path

import kagglehub
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc

"""## Dataset Download"""

data_root = kagglehub.dataset_download("sudipde25/mri-dataset-for-detection-and-analysis")
data_root = Path(data_root)

print("Dataset downloaded to:")
print(data_root)

"""## Dataset Preparation"""

# Binary classification folders
tumor_root = data_root / "NINS_Dataset" / "NINS_Dataset" / "Brain Tumor"
no_tumor_root = data_root / "NINS_Dataset" / "NINS_Dataset" / "Normal"

# Tumor type folders
tumor_type_root = data_root / "NINS_Dataset" / "NINS_Dataset"

print("Tumor folder:", tumor_root)
print("No tumor folder:", no_tumor_root)
print("Tumor type root:", tumor_type_root)

print("\nTumor images:", len(os.listdir(tumor_root)))
print("No tumor images:", len(os.listdir(no_tumor_root)))
print("Tumor type folders:", os.listdir(tumor_type_root))

# Define valid image file formats to ensure only appropriate image types are processed
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}

binary_records = []

# Loop through all files in the tumour folder
for file in tumor_root.iterdir():
    # Check if the file is a valid image
    if file.is_file() and file.suffix.lower() in IMAGE_EXTENSIONS:
        # Add the file path and label tumor to the list
        binary_records.append({
            "filepath": str(file),
            "label": "tumor"
        })
# Loop through all files in the no tumour folder
for file in no_tumor_root.iterdir():
    if file.is_file() and file.suffix.lower() in IMAGE_EXTENSIONS:
        # Add the file path and label no_tumor to the list
        binary_records.append({
            "filepath": str(file),
            "label": "no_tumor"
        })

binary_df = pd.DataFrame(binary_records)

# Print total number of images in the dataset
print("Total binary images:", len(binary_df))
print(binary_df["label"].value_counts())
binary_df.head()

"""## Tumor vs No Tumor Classification"""

# Select a small random sample of tumour and no tumour images
tumor_samples = binary_df[binary_df["label"] == "tumor"].sample(5, random_state=42)
normal_samples = binary_df[binary_df["label"] == "no_tumor"].sample(5, random_state=42)

# Combine both samples into one dataset for visualisation
sample_df = pd.concat([tumor_samples, normal_samples])

plt.figure(figsize=(12,8))

# Loop through each image
for i, (_, row) in enumerate(sample_df.iterrows()):
    img = Image.open(row["filepath"]).convert("RGB")
    # Arrange images in a 2x5 grid
    plt.subplot(2,5,i+1)
    plt.imshow(img)
    plt.title(row["label"])
    plt.axis("off")

plt.tight_layout()
plt.show()

# Create a figure for the class distribution plot
plt.figure(figsize=(6, 4))
sns.countplot(data=binary_df, x="label")
plt.title("Tumor vs No Tumor Distribution")
plt.show()

# Split the dataset into training and temporary set
binary_train_df, binary_temp_df = train_test_split(
    binary_df,
    test_size=0.30,
    stratify=binary_df["label"],
    random_state=42
)
# Split the temporary set into validation and test
binary_val_df, binary_test_df = train_test_split(
    binary_temp_df,
    test_size=0.50,
    stratify=binary_temp_df["label"],
    random_state=42
)
# Print the size of each dataset split
print("Binary train size:", len(binary_train_df))
print("Binary validation size:", len(binary_val_df))
print("Binary test size:", len(binary_test_df))

# Create a mapping to convert text labels into numerical values
binary_label_map = {"no_tumor": 0, "tumor": 1}

binary_train_df["label_id"] = binary_train_df["label"].map(binary_label_map)
binary_val_df["label_id"] = binary_val_df["label"].map(binary_label_map)
binary_test_df["label_id"] = binary_test_df["label"].map(binary_label_map)

IMG_SIZE = 160
BATCH_SIZE = 32
EPOCHS = 12
AUTOTUNE = tf.data.AUTOTUNE

# Function to load and preprocess an image
def load_image(filepath, label):
    image = tf.io.read_file(filepath)
    # Decode the image and ensure it has 3 colour channels
    image = tf.image.decode_image(image, channels=3, expand_animations=False)
    image = tf.image.resize(image, [IMG_SIZE, IMG_SIZE])
    image = tf.cast(image, tf.float32)
    image = tf.keras.applications.efficientnet.preprocess_input(image)
    return image, label

# Define data augmentation to increase dataset diversity
data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.05),
    tf.keras.layers.RandomZoom(0.10)
])
# Function to create a TensorFlow dataset
def make_dataset(dataframe, training=False):
    filepaths = dataframe["filepath"].values
    labels = dataframe["label_id"].values

    ds = tf.data.Dataset.from_tensor_slices((filepaths, labels))

    if training:
        ds = ds.shuffle(len(dataframe), seed=42)

    ds = ds.map(load_image, num_parallel_calls=AUTOTUNE)

    if training:
        ds = ds.map(
            lambda x, y: (data_augmentation(x, training=True), y),
            num_parallel_calls=AUTOTUNE
        )

    # Batch the data and prefetch for better performance
    ds = ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)
    return ds

# Create TensorFlow datasets for training, validation and testing
binary_train_ds = make_dataset(binary_train_df, training=True)
binary_val_ds = make_dataset(binary_val_df, training=False)
binary_test_ds = make_dataset(binary_test_df, training=False)

# Load EfficientNetB0 as the base model (pre-trained on ImageNet)
binary_base_model = tf.keras.applications.EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)
# Freeze the base model so the weights are not updated during training
binary_base_model.trainable = False

binary_inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
# Pass inputs through the pre-trained base model
x = binary_base_model(binary_inputs, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dropout(0.3)(x)
binary_outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)
# Create the full model
binary_model = tf.keras.Model(binary_inputs, binary_outputs)

binary_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

binary_model.summary()

# Define callbacks to improve training and prevent overfitting
binary_callbacks = [
    # Stop training early if validation loss does not improve
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=3,
        restore_best_weights=True
    ),
    # Reduce learning rate if validation loss stops improving
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.3,
        patience=2,
        verbose=1
    )
]
# Train the model using training dataset
binary_history = binary_model.fit(
    binary_train_ds,
    validation_data=binary_val_ds,
    epochs=EPOCHS,
    callbacks=binary_callbacks
)

# Evaluate the model on the test dataset
binary_test_loss, binary_test_accuracy = binary_model.evaluate(binary_test_ds)
print("Binary test loss:", round(binary_test_loss, 4))
print("Binary test accuracy:", round(binary_test_accuracy, 4))

# Get the true labels from the test dataset
binary_y_true = binary_test_df["label_id"].values
binary_y_prob = binary_model.predict(binary_test_ds).flatten()
binary_y_pred = (binary_y_prob >= 0.5).astype(int)

print(classification_report(binary_y_true, binary_y_pred, target_names=["no_tumor", "tumor"]))

# Generate confusion matrix using true labels and predicted labels
binary_cm = confusion_matrix(binary_y_true, binary_y_pred)

plt.figure(figsize=(6, 5))
# Display confusion matrix as a heatmap
sns.heatmap(
    binary_cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["no_tumor", "tumor"],
    yticklabels=["no_tumor", "tumor"]
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Binary Confusion Matrix")
plt.show()

"""## Positive vs False Positive Rate"""

# Calculate False Positive Rate and True Positive Rate
fpr, tpr, thresholds = roc_curve(binary_y_true, binary_y_prob)
# Calculate Area Under the Curve (AUC)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}") # Area Under Curve
# Plot diagonal line (random model baseline)
plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Binary ROC Curve")
plt.legend()
plt.show()

# Define tumour classes for multi-class classification
tumor_classes = ["Glioma", "meningioma"]

tumor_type_records = []
# Loop through each tumour class folder
for class_name in tumor_classes:
    folder = tumor_type_root / class_name

    for file in folder.iterdir():
        if file.is_file() and file.suffix.lower() in IMAGE_EXTENSIONS:
            tumor_type_records.append({
                "filepath": str(file),
                "label": class_name
            })
# Convert collected data into a DataFrame
tumor_type_df = pd.DataFrame(tumor_type_records)

print("Tumor-type dataset size:", len(tumor_type_df))
# Show number of images per class (Glioma vs meningioma)
print(tumor_type_df["label"].value_counts())
tumor_type_df.head()

"""## Tumor Type Classification"""

# Select up to 9 random images from the tumour-type dataset
sample_df = tumor_type_df.sample(min(9, len(tumor_type_df)), random_state=42)

plt.figure(figsize=(10, 8))
# Loop through each sampled image
for i, (_, row) in enumerate(sample_df.iterrows()):
    img = Image.open(row["filepath"]).convert("RGB")
    plt.subplot(3, 3, i + 1)
    plt.imshow(img)
    # Show the tumour type as the title (Glioma or meningioma)
    plt.title(row["label"])
    plt.axis("off")

plt.tight_layout()
plt.show()

# Create a figure for tumour type distribution
plt.figure(figsize=(6, 4))
# Plot the number of images in each tumour class (Glioma vs meningioma)
sns.countplot(data=tumor_type_df, x="label")
plt.title("Tumor Type Distribution")
plt.show()

tumor_train_df, tumor_temp_df = train_test_split(
    tumor_type_df,
    test_size=0.30,
    stratify=tumor_type_df["label"],
    random_state=42
)

tumor_val_df, tumor_test_df = train_test_split(
    tumor_temp_df,
    test_size=0.50,
    stratify=tumor_temp_df["label"],
    random_state=42
)
# Print dataset sizes
print("Tumor-type train size:", len(tumor_train_df))
print("Tumor-type validation size:", len(tumor_val_df))
print("Tumor-type test size:", len(tumor_test_df))

# Get unique tumour labels and sort them
tumor_label_names = sorted(tumor_type_df["label"].unique())
tumor_label_map = {label: i for i, label in enumerate(tumor_label_names)}

# Convert labels to numerical format for training
tumor_train_df["label_id"] = tumor_train_df["label"].map(tumor_label_map)
tumor_val_df["label_id"] = tumor_val_df["label"].map(tumor_label_map)
tumor_test_df["label_id"] = tumor_test_df["label"].map(tumor_label_map)

print("Tumor label map:", tumor_label_map)

tumor_train_ds = make_dataset(tumor_train_df, training=True)
tumor_val_ds = make_dataset(tumor_val_df, training=False)
tumor_test_ds = make_dataset(tumor_test_df, training=False)

# Load EfficientNetB0 as the base model (pre-trained on ImageNet)
tumor_base_model = tf.keras.applications.EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

tumor_base_model.trainable = False

tumor_inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = tumor_base_model(tumor_inputs, training=False)
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dropout(0.3)(x)
tumor_outputs = tf.keras.layers.Dense(len(tumor_label_names), activation="softmax")(x)

tumor_type_model = tf.keras.Model(tumor_inputs, tumor_outputs)

# Compile the model
tumor_type_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

tumor_type_model.summary()

# Define callbacks to improve training and prevent overfitting
tumor_callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=3,
        restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.3,
        patience=2,
        verbose=1
    )
]
# Train the tumour-type classification model
tumor_history = tumor_type_model.fit(
    tumor_train_ds,
    validation_data=tumor_val_ds,
    epochs=EPOCHS,
    callbacks=tumor_callbacks
)

# Evaluate the tumour-type model on the test dataset
tumor_test_loss, tumor_test_accuracy = tumor_type_model.evaluate(tumor_test_ds)
print("Tumor-type test loss:", round(tumor_test_loss, 4))
print("Tumor-type test accuracy:", round(tumor_test_accuracy, 4))

# Get true labels from test dataset
tumor_y_true = tumor_test_df["label_id"].values
tumor_y_prob = tumor_type_model.predict(tumor_test_ds)
tumor_y_pred = np.argmax(tumor_y_prob, axis=1)
# Print classification report (precision, recall, f1-score)
print(classification_report(tumor_y_true, tumor_y_pred, target_names=tumor_label_names))

# Generate confusion matrix using true and predicted labels
tumor_cm = confusion_matrix(tumor_y_true, tumor_y_pred)

plt.figure(figsize=(6, 5))
# Display confusion matrix as a heatmap
sns.heatmap(
    tumor_cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=tumor_label_names,
    yticklabels=tumor_label_names
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Tumor Type Confusion Matrix")
plt.show()

# Function to plot training history (accuracy and loss)
def plot_history(history, title):
    # Extract accuracy and loss values from training history
    acc = history.history["accuracy"]
    val_acc = history.history["val_accuracy"]
    loss = history.history["loss"]
    val_loss = history.history["val_loss"]

    epochs_range = range(len(acc))

    plt.figure(figsize=(12, 5))

    # Plot training vs validation accuracy
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, acc, label="Training Accuracy")
    plt.plot(epochs_range, val_acc, label="Validation Accuracy")
    plt.legend()
    plt.title(f"{title} Accuracy")

    # Plot training vs validation loss
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, loss, label="Training Loss")
    plt.plot(epochs_range, val_loss, label="Validation Loss")
    plt.legend()
    plt.title(f"{title} Loss")

    plt.show()

plot_history(binary_history, "Binary Model")
plot_history(tumor_history, "Tumor Type Model")

"""## Two Stage Prediction System"""

# Function to perform two-stage prediction on a single image
def two_stage_predict(image_path):
    img = Image.open(image_path).convert("RGB")
    img_resized = img.resize((IMG_SIZE, IMG_SIZE))

    # Convert image to array and prepare for model input
    img_array = np.array(img_resized).astype("float32")
    img_array = tf.keras.applications.efficientnet.preprocess_input(img_array)
    img_array = np.expand_dims(img_array, axis=0)

    # Stage 1
    # Predict probability of tumor
    binary_prob = binary_model.predict(img_array, verbose=0)[0][0]
    binary_label = "tumor" if binary_prob >= 0.03 else "no_tumor"

    plt.figure(figsize=(5, 5))
    plt.imshow(img)
    plt.axis("off")

    # If no tumor is detected, stop here
    if binary_label == "no_tumour":
        plt.title(f"Stage 1: no_tumour ({binary_prob:.2%} tumour probability)")
        plt.show()
        print("Final prediction: no_tumour")

    # Stage 2
    # Predict tumor type probabilities
    else:
        tumor_probs = tumor_type_model.predict(img_array, verbose=0)[0]
        tumor_index = np.argmax(tumor_probs)
        tumor_type = tumor_label_names[tumor_index]
        confidence = tumor_probs[tumor_index]

        # Display results
        plt.title(f"Stage 1: tumour | Stage 2: {tumor_type} ({confidence:.2%})")
        plt.show()
        print("Final prediction: tumor")
        print("Tumor type:", tumor_type)
        print("Tumor type confidence:", round(float(confidence), 4))

# Test on one no_tumor image from the binary dataset
example_no_tumor = binary_df[binary_df["label"] == "no_tumor"].sample(1, random_state=42)["filepath"].iloc[0]
print("Testing no_tumor example:")
two_stage_predict(example_no_tumor)

# Test on one tumor image from the binary dataset
example_tumor = binary_df[binary_df["label"] == "tumor"].sample(1, random_state=42)["filepath"].iloc[0]
print("\nTesting tumor example:")
two_stage_predict(example_tumor)

# Save the trained binary and tumour type classification model to file
binary_model.save("binary_tumor_detector.keras")
tumor_type_model.save("tumor_type_classifier.keras")

print("Both models saved successfully.")